# This is a config for E2B sandbox template.
# You can use template ID (w0t5zbqo9jhkoicb9oc0) or template name (blitz) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("blitz") # Sync sandbox
# sandbox = await AsyncSandbox.create("blitz") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('blitz')

team_id = "4c675ca4-1086-47a3-b7e9-f3f3ab4108ab"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "blitz"
template_id = "w0t5zbqo9jhkoicb9oc0"
